/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIndexRouteImport } from './routes/share/index'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PastIndexRouteImport } from './routes/past/index'
import { Route as NewestIndexRouteImport } from './routes/newest/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CommentsIndexRouteImport } from './routes/comments/index'
import { Route as AskIndexRouteImport } from './routes/ask/index'
import { Route as VotedUsernameRouteImport } from './routes/voted/$username'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as PostsUsernameRouteImport } from './routes/posts/$username'
import { Route as PastMonthRouteImport } from './routes/past/$month'
import { Route as CommentsUsernameRouteImport } from './routes/comments/$username'
import { Route as PutAdminSecretRouteImport } from './routes/put.admin.secret'
import { Route as PostIPostIdRouteImport } from './routes/post/i.$postId'
import { Route as PostEPostIdRouteImport } from './routes/post/e.$postId'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/share/',
  path: '/share/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastIndexRoute = PastIndexRouteImport.update({
  id: '/past/',
  path: '/past/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewestIndexRoute = NewestIndexRouteImport.update({
  id: '/newest/',
  path: '/newest/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsIndexRoute = CommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotedUsernameRoute = VotedUsernameRouteImport.update({
  id: '/voted/$username',
  path: '/voted/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsUsernameRoute = PostsUsernameRouteImport.update({
  id: '/posts/$username',
  path: '/posts/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PastMonthRoute = PastMonthRouteImport.update({
  id: '/past/$month',
  path: '/past/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsUsernameRoute = CommentsUsernameRouteImport.update({
  id: '/comments/$username',
  path: '/comments/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PutAdminSecretRoute = PutAdminSecretRouteImport.update({
  id: '/put/admin/secret',
  path: '/put/admin/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIPostIdRoute = PostIPostIdRouteImport.update({
  id: '/post/i/$postId',
  path: '/post/i/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostEPostIdRoute = PostEPostIdRouteImport.update({
  id: '/post/e/$postId',
  path: '/post/e/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/security': typeof SecurityRoute
  '/tips': typeof TipsRoute
  '/comments/$username': typeof CommentsUsernameRoute
  '/past/$month': typeof PastMonthRoute
  '/posts/$username': typeof PostsUsernameRoute
  '/user/$username': typeof UserUsernameRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/voted/$username': typeof VotedUsernameRoute
  '/ask': typeof AskIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/newest': typeof NewestIndexRoute
  '/past': typeof PastIndexRoute
  '/post': typeof PostIndexRoute
  '/share': typeof ShareIndexRoute
  '/post/e/$postId': typeof PostEPostIdRoute
  '/post/i/$postId': typeof PostIPostIdRoute
  '/put/admin/secret': typeof PutAdminSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/security': typeof SecurityRoute
  '/tips': typeof TipsRoute
  '/comments/$username': typeof CommentsUsernameRoute
  '/past/$month': typeof PastMonthRoute
  '/posts/$username': typeof PostsUsernameRoute
  '/user/$username': typeof UserUsernameRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/voted/$username': typeof VotedUsernameRoute
  '/ask': typeof AskIndexRoute
  '/comments': typeof CommentsIndexRoute
  '/login': typeof LoginIndexRoute
  '/newest': typeof NewestIndexRoute
  '/past': typeof PastIndexRoute
  '/post': typeof PostIndexRoute
  '/share': typeof ShareIndexRoute
  '/post/e/$postId': typeof PostEPostIdRoute
  '/post/i/$postId': typeof PostIPostIdRoute
  '/put/admin/secret': typeof PutAdminSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/security': typeof SecurityRoute
  '/tips': typeof TipsRoute
  '/comments/$username': typeof CommentsUsernameRoute
  '/past/$month': typeof PastMonthRoute
  '/posts/$username': typeof PostsUsernameRoute
  '/user/$username': typeof UserUsernameRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/voted/$username': typeof VotedUsernameRoute
  '/ask/': typeof AskIndexRoute
  '/comments/': typeof CommentsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/newest/': typeof NewestIndexRoute
  '/past/': typeof PastIndexRoute
  '/post/': typeof PostIndexRoute
  '/share/': typeof ShareIndexRoute
  '/post/e/$postId': typeof PostEPostIdRoute
  '/post/i/$postId': typeof PostIPostIdRoute
  '/put/admin/secret': typeof PutAdminSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/legal'
    | '/security'
    | '/tips'
    | '/comments/$username'
    | '/past/$month'
    | '/posts/$username'
    | '/user/$username'
    | '/verify/$token'
    | '/voted/$username'
    | '/ask'
    | '/comments'
    | '/login'
    | '/newest'
    | '/past'
    | '/post'
    | '/share'
    | '/post/e/$postId'
    | '/post/i/$postId'
    | '/put/admin/secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/legal'
    | '/security'
    | '/tips'
    | '/comments/$username'
    | '/past/$month'
    | '/posts/$username'
    | '/user/$username'
    | '/verify/$token'
    | '/voted/$username'
    | '/ask'
    | '/comments'
    | '/login'
    | '/newest'
    | '/past'
    | '/post'
    | '/share'
    | '/post/e/$postId'
    | '/post/i/$postId'
    | '/put/admin/secret'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/legal'
    | '/security'
    | '/tips'
    | '/comments/$username'
    | '/past/$month'
    | '/posts/$username'
    | '/user/$username'
    | '/verify/$token'
    | '/voted/$username'
    | '/ask/'
    | '/comments/'
    | '/login/'
    | '/newest/'
    | '/past/'
    | '/post/'
    | '/share/'
    | '/post/e/$postId'
    | '/post/i/$postId'
    | '/put/admin/secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRoute
  LegalRoute: typeof LegalRoute
  SecurityRoute: typeof SecurityRoute
  TipsRoute: typeof TipsRoute
  CommentsUsernameRoute: typeof CommentsUsernameRoute
  PastMonthRoute: typeof PastMonthRoute
  PostsUsernameRoute: typeof PostsUsernameRoute
  UserUsernameRoute: typeof UserUsernameRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  VotedUsernameRoute: typeof VotedUsernameRoute
  AskIndexRoute: typeof AskIndexRoute
  CommentsIndexRoute: typeof CommentsIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  NewestIndexRoute: typeof NewestIndexRoute
  PastIndexRoute: typeof PastIndexRoute
  PostIndexRoute: typeof PostIndexRoute
  ShareIndexRoute: typeof ShareIndexRoute
  PostEPostIdRoute: typeof PostEPostIdRoute
  PostIPostIdRoute: typeof PostIPostIdRoute
  PutAdminSecretRoute: typeof PutAdminSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past/': {
      id: '/past/'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newest/': {
      id: '/newest/'
      path: '/newest'
      fullPath: '/newest'
      preLoaderRoute: typeof NewestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/': {
      id: '/comments/'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voted/$username': {
      id: '/voted/$username'
      path: '/voted/$username'
      fullPath: '/voted/$username'
      preLoaderRoute: typeof VotedUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$username': {
      id: '/posts/$username'
      path: '/posts/$username'
      fullPath: '/posts/$username'
      preLoaderRoute: typeof PostsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past/$month': {
      id: '/past/$month'
      path: '/past/$month'
      fullPath: '/past/$month'
      preLoaderRoute: typeof PastMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/$username': {
      id: '/comments/$username'
      path: '/comments/$username'
      fullPath: '/comments/$username'
      preLoaderRoute: typeof CommentsUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/put/admin/secret': {
      id: '/put/admin/secret'
      path: '/put/admin/secret'
      fullPath: '/put/admin/secret'
      preLoaderRoute: typeof PutAdminSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/i/$postId': {
      id: '/post/i/$postId'
      path: '/post/i/$postId'
      fullPath: '/post/i/$postId'
      preLoaderRoute: typeof PostIPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/e/$postId': {
      id: '/post/e/$postId'
      path: '/post/e/$postId'
      fullPath: '/post/e/$postId'
      preLoaderRoute: typeof PostEPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRoute,
  LegalRoute: LegalRoute,
  SecurityRoute: SecurityRoute,
  TipsRoute: TipsRoute,
  CommentsUsernameRoute: CommentsUsernameRoute,
  PastMonthRoute: PastMonthRoute,
  PostsUsernameRoute: PostsUsernameRoute,
  UserUsernameRoute: UserUsernameRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  VotedUsernameRoute: VotedUsernameRoute,
  AskIndexRoute: AskIndexRoute,
  CommentsIndexRoute: CommentsIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  NewestIndexRoute: NewestIndexRoute,
  PastIndexRoute: PastIndexRoute,
  PostIndexRoute: PostIndexRoute,
  ShareIndexRoute: ShareIndexRoute,
  PostEPostIdRoute: PostEPostIdRoute,
  PostIPostIdRoute: PostIPostIdRoute,
  PutAdminSecretRoute: PutAdminSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
